name: publish-to-npm

on:
  push:
    branches:
      - feature/github-actions

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build package
        uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run lint
      - run: npm run build

      - name: Mockserver run in Docker
        run: docker-compose up -d

      - name: Run tests
        run: npm run test
        env:
          HOST: "localhost"
          PORT: "1090"

      - name: Publish package to NPM registry
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}